url: "https://mathayward.com"
title: "Mat Hayward"
permalink: /instagram/:title/
plugins:
  - jekyll-postcss
  - jekyll-minifier
collections:
  photography:
    output: true
    order:
      - chamonix.md
      - madeira.md
      - iceland.md
      - switzerland.md
      - dolomites.md
      - south-highlands.md
      - west-coast.md
      - lofoten.md
      - lanzarote.md
      - tenerife.md
      - skye-hebrides.md
      - alberta.md
  locations:
    output: true
    order:
      - scotland.md
      - dolomites.md
      - lofoten.md
      - chamonix.md
      - madeira.md
      - iceland.md
      - tenerife.md
      - alberta.md
  peaks:
    output: true
image_base: https://mathayward.imgix.net/
exclude:
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - publish.sh
